name: Submit to Winget

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  submit:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release tag
        id: get_latest_tag
        shell: pwsh  # Use PowerShell
        run: |
          $latest_tag = git describe --tags $(git rev-list --tags --max-count=1)
          Write-Host "Latest tag is: $latest_tag"
          Add-Content -Path $env:GITHUB_ENV -Value "latest_tag=$latest_tag"

      - name: Extract version from tag
        id: get_version
        shell: pwsh  # Use PowerShell
        run: |
          $latest_tag = $env:latest_tag
          $version = $latest_tag -replace '^v', ''
          Write-Host "Version without 'v' is: $version"
          Add-Content -Path $env:GITHUB_ENV -Value "version=$version"
          
      - name: Download release asset
        run: |
          Invoke-WebRequest -Uri "${{ steps.get_release.outputs.assets[0].browser_download_url }}" -OutFile "HeadsetControl-GUI.zip"

      - name: Calculate SHA256
        id: sha256
        run: |
          $hash = (Get-FileHash -Algorithm SHA256 -Path .\HeadsetControl-GUI.zip).Hash
          echo "::set-output name=hash::$hash"

      - name: Create winget manifest
        run: |
          $manifest = @"
          PackageIdentifier: LeoKlaus.HeadsetControl-GUI
          PackageVersion: ${{ steps.get_version.outputs.version }}
          PackageLocale: en-US
          Publisher: LeoKlaus
          PublisherUrl: https://github.com/LeoKlaus
          PackageName: HeadsetControl-GUI
          PackageUrl: https://github.com/LeoKlaus/HeadsetControl-GUI
          License: MIT
          LicenseUrl: https://github.com/LeoKlaus/HeadsetControl-GUI/blob/main/LICENSE
          ShortDescription: A GUI for headsetcontrol, a tool for controlling certain headsets
          Installers:
            - Architecture: x64
              InstallerType: zip
              InstallerUrl: ${{ steps.get_release.outputs.assets[0].browser_download_url }}
              InstallerSha256: ${{ steps.sha256.outputs.hash }}
              NestedInstallerType: portable
              NestedInstallerFiles:
                - RelativeFilePath: HeadsetControl-GUI.exe
          ManifestType: singleton
          ManifestVersion: 1.0.0
          "@
          $manifest | Out-File -FilePath .\LeoKlaus.HeadsetControl-GUI.yaml -Encoding utf8

      - name: Install Winget-Create
        run: |
          Invoke-WebRequest -Uri https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe --version

      - name: Validate manifest
        run: |
          .\wingetcreate.exe validate .\LeoKlaus.HeadsetControl-GUI.yaml

      - name: Submit manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\wingetcreate.exe submit .\LeoKlaus.HeadsetControl-GUI.yaml --token $env:GITHUB_TOKEN
